# Generated by Django 3.1.7 on 2021-03-03 03:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('NEWS', 'news'), ('TECHNOLOGY', 'technology'), ('LITERATURE', 'literature'), ('LIFESTYLE', 'lifestyle'), ('HEALTH', 'health'), ('ART', 'art'), ('MARKET', 'market'), ('OTHERS', 'others'), ('FEATURE', 'feature'), ('NATIONAL', 'national'), ('DIASPORA', 'diaspora'), ('ENTERTAINMENT', 'entertainment'), ('SPORTS', 'sports'), ('WORLD', 'world'), ('OPINION', 'opinion'), ('BUSINESS', 'business'), ('KOSELI', 'koseli'), ('INTERVIEW', 'interview'), ('BLOG', 'blog'), ('POLITICS', 'politics'), ('NEPALI-BRAND', 'nepali-brand'), ('KINMEL', 'kinmel'), ('GHUMPHIR', 'ghumphir')], max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('images_link', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
