# Generated by Django 3.1.1 on 2021-03-03 06:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='news_choices',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NEWS', 'news'), ('TECHNOLOGY', 'technology'), ('LITERATURE', 'literature'), ('LIFESTYLE', 'lifestyle'), ('HEALTH', 'health'), ('ART', 'art'), ('MARKET', 'market'), ('OTHERS', 'others'), ('FEATURE', 'feature'), ('NATIONAL', 'national'), ('DIASPORA', 'diaspora'), ('ENTERTAINMENT', 'entertainment'), ('SPORTS', 'sports'), ('WORLD', 'world'), ('OPINION', 'opinion'), ('BUSINESS', 'business'), ('KOSELI', 'koseli'), ('INTERVIEW', 'interview'), ('BLOG', 'blog'), ('POLITICS', 'politics'), ('NEPALI-BRAND', 'nepali-brand'), ('KINMEL', 'kinmel'), ('GHUMPHIR', 'ghumphir')], max_length=191),
        ),
    ]
